services:
  - type: web
    name: Asfalis-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn -w 1 --threads 4 --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Asfalis-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

databases:
  - name: Asfalis-db
    databaseName: Asfalis
    user: Asfalis_user
    plan: free # optional
    region: singapore

